pipeline {
    agent any 
    
    stages{
        stage("Clone Code"){
            steps {
                echo "Cloning the code"
                git branch: 'main', credentialsId: 'note-app', url: 'https://github.com/dipali-coditas/calci.git'
            }
        }
        stage("Build"){
            steps {
                echo "Building the image"
                sh "docker build -t calci-app ."
            }
        }
        stage("Push to Docker Hub"){
            steps {
                echo "Pushing the image to docker hub"
                withCredentials([usernamePassword(credentialsId:"dockerHub",passwordVariable:"dockerHubPass",usernameVariable:"dockerHubUser")]){
                sh "docker tag calci-app ${env.dockerHubUser}/calci-app:latest"
                sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPass}"
                sh "docker push ${env.dockerHubUser}/calci-app:latest"
                }
            }
        }
        stage("Deploy"){
            steps {
                echo "Deploying the container"
                sh "docker run -d -p 8002:8002 calci-app"
                
            }
        }
    }
}